---
# Copyright 2022 The KubeFin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: kubefin
data:
  config.yaml: |-
    receivers:
      prometheus_simple:
        # The allowed min period is 15s
        collection_interval: 15s
        endpoint: "127.0.0.1:8080"
        metrics_path: "/metrics"
        use_service_account: false
    processors:
      batch:
      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s
    extensions:
      zpages: {}
      memory_ballast:
        # Memory Ballast size should be max 1/3 to 1/2 of memory.
        size_mib: 683
    exporters:
      prometheusremotewrite:
        namespace: ""
        endpoint: "{REMOTE_WRITE_ADDRESS}"
    service:
      telemetry:
      extensions: [zpages, memory_ballast]
      pipelines:
        metrics:
          receivers: [prometheus_simple]
          processors: [memory_limiter, batch]
          exporters: [prometheusremotewrite]
