---
# Copyright 2022 The KubeFin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefin-cost-analyzer
  namespace: kubefin-system
  labels:
    app.kubernetes.io/component: kubefin-cost-analyzer
    app.kubernetes.io/name: kubefin
    app.kubernetes.io/version: devel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubefin-cost-analyzer
  template:
    metadata:
      labels:
        app: kubefin-cost-analyzer
        app.kubernetes.io/component: kubefin-cost-analyzer
        app.kubernetes.io/name: kubefin
        app.kubernetes.io/version: devel
    spec:
      containers:
        - name: kubefin-cost-analyzer
          # This is the Go import path for the binary that is containerized
          # and substituted here.
          image: ko://kubefin.dev/kubefin/cmd/kubefin-cost-analyzer
          args:
            - --v=4
          env:
            - name: QUERY_BACKEND_ENDPOINT
              value: "http://mimir.kubefin-system.svc.cluster.local:9009/prometheus"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          ports:
            - name: healthcheck
              containerPort: 9090
            - name: server
              containerPort: 8080
        - name: kubefin-dashboard
          image: kubefin/kubefin-dashboard:{KUBEFIN_DASHBOARD_VERSION}
          ports:
            - name: server
              containerPort: 3000
            - name: healthcheck
              containerPort: 3000
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: kubefin-cost-analyzer-service
  namespace: kubefin-system
  labels:
    app: kubefin-cost-analyzer
    app.kubernetes.io/component: kubefin-cost-analyzer
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: kubefin
spec:
  selector:
    app: kubefin-cost-analyzer
  ports:
    - name: kubefin-api
      port: 8080
      targetPort: 8080
    - name: kubefin-dashboard
      port: 3000
      targetPort: 80
  type: ClusterIP
